# Generated by Django 3.0.2 on 2020-02-17 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ais',
            name='author',
        ),
        migrations.DeleteModel(
            name='Obj',
        ),
        migrations.DeleteModel(
            name='AIs',
        ),
    ]
